apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql 
  replicas: 2
  template: 
    metadata: 
      labels: 
       app: mysql 
    spec: 
      containers: 
        - name: mysql 
          image: mysql:latest 
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: glusterfs-mysql-pvc
