apiVersion: apps/v1
kind: StatefulSet 
metadata: 
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql 
  serviceName: glusterfs
  replicas: 1
  template: 
    metadata: 
      labels: 
       app: mysql 
    spec: 
      containers: 
      - name: mysql 
        image: mysql:latest 
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      resources:
        requests:
          storage: 8Gi 
      accessModes:
      - ReadWriteMany
