apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-mysql-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "models"
    readOnly: false

